// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDoWl-LPy6Xq41OvdXDAtBoUa83TdQj0',
    appId: '1:1047074667222:web:6bc3673d512c943d0ae777',
    messagingSenderId: '1047074667222',
    projectId: 'hostel-management-38192',
    authDomain: 'hostel-management-38192.firebaseapp.com',
    storageBucket: 'hostel-management-38192.appspot.com',
    measurementId: 'G-QH4DE62QD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YLbrMIfU53vpAeCELr-Ga_AHCC1Yopc',
    appId: '1:1047074667222:android:00ce52805533270a0ae777',
    messagingSenderId: '1047074667222',
    projectId: 'hostel-management-38192',
    storageBucket: 'hostel-management-38192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehDyBLyLx7LLeenGxZCpAVFUlzhiPLRU',
    appId: '1:1047074667222:ios:19b4f46f26a393fa0ae777',
    messagingSenderId: '1047074667222',
    projectId: 'hostel-management-38192',
    storageBucket: 'hostel-management-38192.appspot.com',
    iosBundleId: 'com.example.hostManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCehDyBLyLx7LLeenGxZCpAVFUlzhiPLRU',
    appId: '1:1047074667222:ios:19b4f46f26a393fa0ae777',
    messagingSenderId: '1047074667222',
    projectId: 'hostel-management-38192',
    storageBucket: 'hostel-management-38192.appspot.com',
    iosBundleId: 'com.example.hostManagement',
  );
}
